name: Build & Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run TypeScript type check
              run: npm run type-check

            - name: Build
              run: npm run build-only

            - name: Start Vite preview
              run: npx vite preview --port=5173 --host 0.0.0.0 &

            - name: Wait for server
              run: npx wait-on http://localhost:5173

            - name: Install Playwright Chromium
              run: npx playwright install chromium

            - name: Debug server
              run: curl -v http://localhost:5173 || echo "Server not responding"

            - name: Run Playwright tests
              env:
                  CI: true
                  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
                  FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
                  FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
                  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
                  FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
                  FIREBASE_MESSAGE_SENDER_ID: ${{ secrets.FIREBASE_MESSAGE_SENDER_ID }}
                  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
                  FIREBASE_DB_NAME: ${{ secrets.FIREBASE_DB_NAME }}
                  OMDB_APIKEY: ${{ secrets.OMDB_APIKEY }}
              run: npx playwright test --reporter=list --trace=on

            - uses: actions/upload-artifact@v4
              with:
                  name: trace-logs
                  path: path/to/trace.zip
