name: Build & Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        env:
            CI: true
            VITE_FIREBASE_APIKEY: ${{ secrets.VITE_FIREBASE_APIKEY }}
            VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
            VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
            VITE_FIREBASE_DB_NAME: ${{ secrets.VITE_FIREBASE_DB_NAME }}
            VITE_FIREBASE_DB_URL: ${{ secrets.VITE_FIREBASE_DB_URL }}
            VITE_FIREBASE_MESSAGE_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGE_SENDER_ID }}
            VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
            VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
            VITE_OMDB_APIKEY: ${{ secrets.VITE_OMDB_APIKEY }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version-file: .nvmrc
                  cache: 'npm'
            - run: npm ci
            - run: npm run build-only
            - run: npx vite preview --port=5173 --host 0.0.0.0 &
            - uses: actions/cache@v3
              with:
                  path: ~/.cache/ms-playwright
                  key: playwright-${{ runner.os }}-chromium
                  restore-keys: |
                      playwright-${{ runner.os }}-chromium
            - run: npx playwright install chromium
            - run: npx playwright test --reporter=list --trace=on --timeout=15000
