name: Setup Node.js

on:
    workflow_call:

jobs:
    setup-node:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: .nvmrc
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci
