name: TypeScript Check

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    setup-node-job:
        uses: ./.github/workflows/setup-node.yml

    type-check-job:
        runs-on: ubuntu-latest
        needs: setup-node-job
        steps:
            - run: npm run type-check
